"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup
from os import walk


APP = ['sabatinator.py']
APP_NAME="Sabatinator 2.0"
DATA_FILES = []

for (dirpath, dirnames, filenames) in walk("/Users/mac/Desktop/SABATINATOR2.0/fotosJDA"):
    DATA_FILES.extend(filenames)
    break

OPTIONS = {'argv_emulation': True,
           'iconfile': 'jardim.icns',
           'plist': {
            'CFBundleName': APP_NAME,
            'CFBundleDisplayName': APP_NAME,
            'CFBundleGetInfoString': "Sabatinator 2.0",
            'CFBundleVersion': "0.1.0",
            'CFBundleShortVersionString': "0.1.0",
            'NSHumanReadableCopyright': u"Copyright  2016, Guilherme Monteiro, All Rights Reserved"
           }
        }

setup(
    name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
